batch_size: 64
bidirectional: true
binarize_blocks: true
checkpoint_dir: /srv/local1/estengel/models/unet_bisk_glove
compute_block_dist: true
cuda: 0
do_filter: true
do_one_hot: true
do_reconstruction: false
dropout: 0.3
embedder: glove
embedding_dim: 100
embedding_file: /srv/local1/estengel/glove/glove.6B.100d.txt
encoder: lstm
encoder_hidden_dim: 64
encoder_num_layers: 2
generate_after_n: 201
learn_rate: 0.0001
max_seq_length: 40
mlp_hidden_dim: 32
mlp_num_layers: 2
num_blocks: 1
num_epochs: 200
num_models_to_keep: 5
resolution: 64
resume: false
share_level: encoder
test: false
top_only: true
train_path: blocks_data/trainset_v2.json
traj_type: flat
unet_hc_large: 32
unet_hc_small: 16
unet_kernel_size: 5
unet_num_layers: 5
unet_out_channels: 128
unet_stride: 2
unet_type: unet_with_attention
val_path: blocks_data/small_devset.json
zero_weight: 0.05
