augment_by_flipping: true
augment_by_rotating: false
augment_language: false
batch_size: 64
channels: 6
checkpoint_dir: 
cuda: 0
dropout: 0.4
embed_dropout: 0.33
embedder: random
embedding_dim: 300
embedding_file: None
ff_dim: 512
gamma: 0.7
generate_after_n: 401
hidden_dim: 256
init_scale: 64
learn_rate: 0.0
leave_out_color: None
lr_factor: 1.0
max_seq_length: 40
n_classes: 2
n_heads: 8
n_shared_layers: 6
n_split_layers: 4
next_weight: 1.0
num_epochs: 400
num_models_to_keep: 5
output_type: per-patch
overfit: false
patch_size: 4
path: /srv/local1/estengel/gr_data_sim/
pos_encoding_type: fixed-separate
prev_weight: 1.0
resolution: 64
resume: false
score_type: block_acc
seed: 12
split_type: random
task_type: stacks
test: false
warmup: 2000
zero_weight: 0.1
do_reconstruction: True 
