batch_size: 18
binarize_blocks: true
channels: 6
checkpoint_dir: /srv/local1/estengel/models/transformer_tune_images_bert/0.38_0.2_0_2_4_2000
cuda: 0
do_filter: true
do_one_hot: false
do_reconstruction: false
do_regression: false
do_residual: false
dropout: 0.4
embed_dropout: 0.33
embedder: bert-base-uncased
embedding_dim: 768
embedding_file: null
encoder_type: TransformerEncoder
ff_dim: 1024
gamma: 0.7
generate_after_n: 401
hidden_dim: 256
#image_path: blocks_data/generated_images/data_32mm/data/
image_path: null
include_depth: true
init_scale: 4
learn_rate: 0.0
lr_factor: 1.0
max_seq_length: 40
n_classes: 2
n_epochs_pre_valid: 25
n_heads: 4
n_shared_layers: 0
n_split_layers: 2
next_weight: 1.0
num_blocks: 1
num_epochs: 30
num_models_to_keep: 1
out_path: null
output_type: per-patch
patch_size: 2
pos_encoding_type: fixed-separate
prev_weight: 1.0
resolution: 64
resume: false
score_type: acc
seed: 12
test: false
test_path: null
top_only: true
train_path: blocks_data/trainset_v2.json
traj_type: flat
val_path: blocks_data/devset.json
warmup: 2000
zero_weight: 0.2
