# DATA 
train_path: "blocks_data/singleset.json"
val_path: "blocks_data/singleset.json"
#image_path: blocks_data/generated_images/data_32mm/data/
num_blocks: 1
binarize_blocks: True
traj_type: "flat"
batch_size: 32
max_seq_length: 40
do_filter: True
do_one_hot: False
channels: 1
top_only: True
resolution: 64
zero_weight: 0.01
do_regression: True
do_reconstruction: True

# LANGUAGE EMBEDDER
embedder: random
embedding_dim: 15

# TRANSFORMER
patch_size: 4
n_shared_layers: 2
n_split_layers: 2
n_classes: 2
n_heads: 2
hidden_dim: 64
ff_dim: 128
dropout: 0.00
embed_dropout: 0.00
output_type: "per-patch" 
pos_encoding_type: fixed-2d-separate

# MISC
cuda: 0
learn_rate: 0.00
warmup: 400
checkpoint_dir: "" #"models/language_pretrain"
num_epochs: 200
generate_after_n: 198
score_type: "acc"
