# DATA 
train_path: "blocks_data/singleset.json"
val_path: "blocks_data/singleset.json"
num_blocks: 1
binarize_blocks: True
traj_type: "flat"
batch_size: 32
max_seq_length: 40
do_filter: True
do_one_hot: True
top_only: True
resolution: 64
zero_weight: 0.01

# LANGUAGE EMBEDDER
embedder: random
embedding_dim: 15

# TRANSFORMER
encoder_type: ResidualTransformerEncoder
patch_size: 4
n_shared_layers: 2
n_split_layers: 2
n_classes: 2
n_heads: 2
hidden_dim: 64
ff_dim: 128
dropout: 0.00
embed_dropout: 0.00
output_type: "per-patch" 
pos_encoding_type: fixed-2d-separate
do_residual: false

# MISC
cuda: 0
learn_rate: 0.00
warmup: 400 
checkpoint_dir: "" #"models/language_pretrain"
num_epochs: 100
generate_after_n: 98
score_type: "tele_score"
