batch_size: 64
binarize_blocks: true
checkpoint_dir: ""
cuda: 0
do_filter: true
do_one_hot: false
dropout: 0.4
embed_dropout: 0.33
embedder: bert-base-uncased
embedding_dim: 768
#embedding_file: /srv/local1/estengel/glove/glove.6B.100d.txt
ff_dim: 1024
gamma: 0.7
generate_after_n: 401
hidden_dim: 256
learn_rate: 0.0
lr_factor: 1.0
max_seq_length: 40
n_classes: 2
n_heads: 4
n_shared_layers: 4
n_split_layers: 2
next_weight: 1
num_blocks: 1
channels: 6
num_epochs: 400
num_models_to_keep: 5
output_type: per-patch
patch_size: 4
pos_encoding_type: fixed-separate
prev_weight: 1
resolution: 64
resume: false
seed: 12
test: false
top_only: true
train_path: blocks_data/trainset_v2.json
val_path: blocks_data/devset.json
image_path: blocks_data/generated_images/data_32mm/data/
traj_type: flat
warmup: 1000
zero_weight: 0.2
