# DATA 
train_path: "blocks_data/trainset_v2.json"
val_path: "blocks_data/small_devset.json"
image_path: "blocks_data/generated_images/color_data" 
num_blocks: 1
binarize_blocks: True
traj_type: "flat"
batch_size: 32
max_seq_length: 40
do_filter: True
#do_one_hot: True
do_one_hot: False
channels: 6
top_only: True
resolution: 64
zero_weight: 0.01

# LANGUAGE EMBEDDER
embedder: "bert-base-uncased"
embedding_dim: 768

# TRANSFORMER
patch_size: 4
n_shared_layers: 4
n_split_layers: 2
n_classes: 2
n_heads: 4
hidden_dim: 256
ff_dim: 1024
dropout: 0.4
embed_dropout: 0.33
output_type: "per-patch" 
pos_encoding_type: fixed-separate

# MISC
cuda: 0
learn_rate: 0.00
warmup: 1000
checkpoint_dir: "" #"models/language_pretrain"
num_epochs: 100
generate_after_n: 99
score_type: "acc"
