batch_size: 18
binarize_blocks: true
channels: 6
checkpoint_dir: 
cuda: 0
do_filter: true
do_one_hot: false
do_reconstruction: false
do_regression: false
do_residual: false
dropout: 0.4
embed_dropout: 0.33
embedder: bert-base-uncased
embedding_dim: 768
embedding_file: None
encoder_type: TransformerEncoder
ff_dim: 1024
gamma: 0.7
n_epochs_pre_valid: 0
generate_after_n: 401
hidden_dim: 256
image_path: blocks_data/generated_images/data_32mm/data/
init_scale: 4
learn_rate: 0.0
lr_factor: 1.0
max_seq_length: 40
n_classes: 2
n_heads: 4
n_shared_layers: 4
n_split_layers: 2
next_weight: 1.0
num_blocks: 1
num_epochs: 400
num_models_to_keep: 1
output_type: per-patch
patch_size: 2
pretrained_weights: /srv/local1/estengel/models/transformer_bisk_bert_no_reconstruction/best.th
pos_encoding_type: fixed-img-only
prev_weight: 1.0
resolution: 64
resume: false
score_type: tele_score
seed: 12
test: false
test_path: null
top_only: true
train_path: blocks_data/trainset_v2.json
traj_type: flat
val_path: blocks_data/devset.json
warmup: 1000
zero_weight: 0.2
