# DATA 
path: "/srv/local1/estengel/gr_data/"
batch_size: 32
max_seq_length: 40
resolution: 64
split_type: "random"
task_type: "rows" 
augment_by_flipping: False
augment_language: False 

checkpoint_dir: 
cuda: 0
dropout: 0.4
embed_dropout: 0.33
embedder: bert-base-uncased
embedding_dim: 768
embedding_file: None
ff_dim: 512
gamma: 0.7
generate_after_n: 401
hidden_dim: 256
learn_rate: 0.0
lr_factor: 1.0
n_classes: 2
n_heads: 4
n_shared_layers: 2
n_split_layers: 2
next_weight: 1.0
num_epochs: 400
num_models_to_keep: 5
output_type: per-patch
patch_size: 4
pos_encoding_type: fixed-separate
prev_weight: 1.0
resume: false
score_type: acc
seed: 12
test: false
warmup: 400
zero_weight: 0.2
