augment_by_flipping: false
augment_language: false
batch_size: 64
checkpoint_dir: 
cuda: 0
dropout: 0.4
embed_dropout: 0.33
embedder: bert-base-uncased
embedding_dim: 768
embedding_file: None
ff_dim: 512
gamma: 0.7
generate_after_n: 401
hidden_dim: 256
learn_rate: 0.0
leave_out_color: null
lr_factor: 1.0
max_seq_length: 40
n_classes: 2
n_heads: 4
n_shared_layers: 6
n_split_layers: 4
next_weight: 1.0
num_epochs: 300
num_models_to_keep: 5
output_type: per-patch
overfit: false
patch_size: 4
path: /srv/local1/estengel/gr_data/
pos_encoding_type: fixed-separate
prev_weight: 1.0
resolution: 64
resume: false
score_type: acc
seed: 12
split_type: random
task_type: rows
test: false
warmup: 100
zero_weight: 0.1
