augment_by_flipping: true
augment_by_rotating: false
augment_language: false
augment_with_noise: true
batch_size: 32
bidirectional: true
channels: 6
checkpoint_dir: 
color_pair: null
compute_block_dist: true
cuda: 0
do_reconstruction: true
dropout: 0.3
embedder: random
embedding_dim: 300
embedding_file: null
encoder: lstm
encoder_hidden_dim: 128
encoder_num_layers: 2
generate_after_n: 201
learn_rate: 0.0001
leave_out_color: None
max_seq_length: 40
mlp_hidden_dim: 32
mlp_num_layers: 2
next_weight: 1
num_epochs: 200
num_models_to_keep: 5
overfit: false
path: blocks_data/good_robot_sim
prev_weight: 1
resolution: 64
resume: false
seed: 12
share_level: encoder
split_type: random
task_type: rows-and-stacks
test: false
unet_hc_large: 32
unet_hc_small: 16
unet_kernel_size: 5
unet_num_layers: 5
unet_out_channels: 128
unet_stride: 2
unet_type: unet_with_attention
zero_weight: 0.05
